# Tests for FastAPI endpoints

### Get list of categories
GET http://localhost:8000/v1/categories
Accept: application/json

### Get list of genders
GET http://localhost:8000/v1/genders
Accept: application/json

### Get list of regions
GET http://localhost:8000/v1/regions
Accept: application/json

### Get list of filters
GET http://localhost:8000/v1/filters
Content-Type: application/json
Accept: application/json

### Search creators with no filters
POST http://localhost:8000/v1/search_creators
Content-Type: application/json
Accept: application/json

{
  "filters": {
    "gender": null,
    "categories": []
  }
}

### Login existing user
POST http://localhost:8000/v1/auth/login
Content-Type: application/x-www-form-urlencoded
Accept: application/json

username = desfrutando.vida@test.com &
password = 00000001

### Get user info for logged existing user
GET http://localhost:8000/v1/auth/user
Accept: application/json

### Logout existing user
POST http://localhost:8000/v1/auth/logout
Accept: application/json

### Signup new user
POST http://localhost:8000/v1/auth/signup
Content-Type: application/x-www-form-urlencoded
Accept: application/json

username = bot@auraz.com.br &
password = 12345678

### Get user info for logged new user
GET http://localhost:8000/v1/auth/user
Accept: application/json

### Logout new user
POST http://localhost:8000/v1/auth/logout
Accept: application/json
